version: '2'
services:
  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./app/data:/var/www/app/data
      - ./app/plugins:/var/www/app/plugins
      - ./nginx/ssl:/etc/nginx/ssl
    environment:
      DATABASE_URL: mysql://kanboard:kanboard-secret@db/kanboard
      TZ: Asia/Seoul
  db:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: kanboard
      MYSQL_USER: kanboard
      MYSQL_PASSWORD: kanboard-secret
      TZ: Asia/Seoul
    ports:
      - "3306:3306"  
    volumes:
      - db:/var/lib/mysql
volumes:
  kanboard_data:
  kanboard_plugins:
  kanboard_ssl:
  db: